AWSTemplateFormatVersion: "2010-09-09"
Resources: 
  S3Bucket: 
    Type: "AWS::S3::Bucket"
  EC2:
    Type: "AWS::EC2::Instance"
    Properties: 
      ImageId: "ami-032d6db78f84e8bf5"
      InstanceType: "t2.micro"
      SubnetId: "subnet-0b12f3b92cd501025"
      BlockDeviceMappings:
        -
          DeviceName: "/dev/xvda"
          Ebs:
            VolumeType: "gp2"
            VolumeSize: "8"
      Tags:
      - Key: "Name"
        Value: "Ec2_madeFrom_codepipeline"
      SecurityGroupIds: 
      - "sg-0bece73851aac2346"
Outputs: 
  BucketName: 
    Value: 
      Ref: "S3Bucket"
    Description: "Name of Amazon S3 bucket."
  EC2InstanceID: 
    Value: 
      Ref: "EC2"
    Description: "Id of the Amazon EC2."  